carts/urls.py
from django.urls import path
from carts.views import (
    cartHome,
    cartUpdate,
    checkoutHome
) 

app_name = 'carts'

urlpatterns = [
    path('', cartHome, name='home'),
    path('update/', cartUpdate, name='update'),
    path('checkout/', checkoutHome, name='checkout'),
]

jeffersonsmedia/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('search/', include('search.urls',namespace='search')),
    path('cart/', include('carts.urls',namespace='cart')),
    path('orders/', include('orders.urls',namespace='orders')),
    path('products/', include('products.urls',namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('billing/', include('billing.urls',namespace='billing')),
    path('logout/', LogoutView.as_view(), name='usr_logout'),
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace='home')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.urls import path
from search.views import (
    SearchProductView,
) 

app_name = 'tags'

urlpatterns = [
    path('', SearchProductView.as_view(), name='query'),
]

carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, m2m_changed

from products.models import Product

User = settings.AUTH_USER_MODEL


class CartManeger(models.Manager):
    
    def newOrGet(self,request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self,user=None):
        user_obj=None
        print(user)
        if user is not None:
            if user.is_authenticated:
                user_obj=user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    total = models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManeger()

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = "Cart"


def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for item in products:
            total += item.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
    
m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)


def pre_save_cart_receiver(sender,instance,*args,**kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.16)
    else:
        instance.total = 0.00
    
pre_save.connect(pre_save_cart_receiver,sender=Cart)

carts/views.py
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from orders.models import Order
from carts.models import Cart
from products.models import Product


def cartHome(request):
    cart_obj, new_obj = Cart.objects.newOrGet(request)
    products = cart_obj.products.all()
    context={
        'cart':cart_obj
    }
    content_type=None
    return render(request, 'carts/home.html',context, content_type)


def cartUpdate(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect('cart:home')
        cart_obj, new_obj = Cart.objects.newOrGet(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    # return redirect(product_obj.get_absolute_url())
    return redirect('cart:home')


def checkoutHome(request):
    cart_obj, cart_created = Cart.objects.newOrGet(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('cart:home')
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    user = request.user
    billing_profile = None
    login_form = LoginForm()
    guest_form = GuestForm()

    if user.is_authenticated:
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(
            user=user, email=user.email)
    context={
        'object':order_obj,
        'billing_profile':billing_profile,
        'login_form':login_form,
    }
    content_type=None
    return render(request,'carts/checkout.html',context, content_type)

carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block body %}


{% if not billing_profile %}
{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
{% else %}
<div class="mx-auto col-12 col-sm-12 col-md-11 col-lg-9 col-xl-7">
    <h1> Checkout </h1>
    <p> Cart Total: {{ object.cart.total }} </p>
    <p> Shipping Total: {{ object.shipping_total }} </p>
    <p> Order Total: {{ object.total }} </p>
</div>
{% endif %}

{% endblock body %}

carts/templates/carts/home.html
{% extends 'base.html' %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block body %}
{% url 'cart:checkout' as checkout_url %}
<div class="mx-auto col-12 col-sm-12 col-md-11 col-lg-9 col-xl-7">
    <h1>cart 1</h1>
    {% if cart.products.exists %}
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Category</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for product in cart.products.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ product.category }}</td>
                <td>
                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </td>
                <td>{{ product.price }}</td>
                <td>
                    {% include 'products/snippets/update_cart.html' with product=product cart=cart in_cart=True %}
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td class="text-right" colspan="3">
                    <b> Subtotal : </b>
                </td>
                <td colspan="2">{{ cart.subtotal }}</td>
            </tr>
            <tr>
                <td class="text-right" colspan="3">
                    <b> Total : </b>
                </td>
                <td colspan="2">{{ cart.total }}</td>
            </tr>
            <tr>
                <td class="text-right" colspan="3"></td>
                <td colspan="2"><a class="btn btn-sm btn-block btn-success" href="{{ checkout_url }}"> Ckeckout </a></td>
            </tr>
        </tbody>
    </table>
    {% else %}
    <div class="container-fluid">
        <hr>
        <p class="lead text-center"> Cart is Empty </p>
        <hr>
    </div>
    {% endif %}
</div>
{% endblock body %}