billing/urls.py
from django.urls import path
from accounts.views import (
    loginPage,
    registerPage)


app_name = 'billing'


urlpatterns = [
    path('login/', loginPage, name='usr_login'),
    path('register/', registerPage, name='usr_registration'),
]

carts/urls.py
from django.urls import path
from carts.views import (
    cartHome,
    cartUpdate,
    checkoutHome
) 

app_name = 'carts'

urlpatterns = [
    path('', cartHome, name='home'),
    path('update/', cartUpdate, name='update'),
    path('checkout/', checkoutHome, name='checkout'),
]

jeffersonsmedia/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('search/', include('search.urls',namespace='search')),
    path('cart/', include('carts.urls',namespace='cart')),
    path('orders/', include('orders.urls',namespace='orders')),
    path('products/', include('products.urls',namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('billing/', include('billing.urls',namespace='billing')),
    path('logout/', LogoutView.as_view(), name='usr_logout'),
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace='home')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import (
    ProductListView,
    ProductDetailSlugView,
    addProduct,
    # home,
    # product_list_view,
    # ProductFeaturedListView,
    # product_detail_view,
    # ProductDetailView,
    # ProductFeaturedDetailView
) 

app_name = 'products'

urlpatterns = [
    path('add_item/', addProduct, name='add_item'),
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail')
    
    # path('products/', ProductListView.as_view(), name='products'),
    # path('', home, name='home_page'),
    # path('products_fbv/', product_list_view, name='products_fbv'),
    # path('featured/', ProductFeaturedListView.as_view(), name='featured'),
    # path('products_fbv/<int:pk>/', product_detail_view, name='product_detail_fbv'),
    # # path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    # path('featured/<int:pk>/', ProductFeaturedDetailView.as_view(), name='featured_detail')
]

tags/urls.py
from django.urls import path
from search.views import (
    SearchProductView,
) 

app_name = 'tags'

urlpatterns = [
    path('', SearchProductView.as_view(), name='query'),
]

templates/base/css.html
{% load static %}

templates/base/js.html
{% load static %}

templates/base/navbar.html
{% load static %}
{% url 'products:list' as products_list %}
{% url 'products:add_item' as add_item %}
{% url 'accounts:usr_registration' as usr_registration %}
{% url 'accounts:usr_login' as usr_login %}
{% url 'usr_logout' as usr_logout %}
{% url 'cart:home' as cart_url %}


<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header ml-md-2 mx-auto">
            <a class="navbar-brand" href="{{products_list}}">
                <img src="{% static 'images/logo99.png' %}" height="40" class="image-fluid" alt="Logo">
                <img src="{% static 'images/brand.jpeg' %}" height="40" class="image-fluid ml-2 ml-lg-3" alt="Brand">
            </a>
        </div>
        <div class="container-fluid mx-auto">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-link {% if request.path == products_list %}active{% endif %}">
                        <a href="{{products_list}}">Products</a>
                    </li>
                </ul>
                <ul class="navbar-nav mx-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-link {% if request.path == usr_logout %}active{% endif %}">
                        <a href="{{usr_logout}}">
                            Logout
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-link {% if request.path == usr_registration %}active{% endif %}">
                        <a href="{{usr_registration}}">
                            <span class="glyphicon glyphicon-user"></span>
                            SignUp
                        </a>
                    </li>
                    <li class="nav-link {% if request.path == usr_login %}active{% endif %}">
                        <a href="{{usr_login}}">
                            <span class="glyphicon glyphicon-log-in"></span>
                            Login
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav mx-auto">
                    {% if request.session.cart_items %}
                    <li class="nav-link {% if request.path == cart_url %}active{% endif %}">
                        <a href="{{cart_url}}">
                            <span class="badge badge-primary badge-pill">
                                {{ request.session.cart_items }}
                            </span>
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% include 'search/snippets/search_form.html'%}
            </div>
        </div>
    </div>
</nav>